/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LinearCallbackRouteImport } from './routes/linear.callback'
import { Route as HuddlesHuddleSlugRouteImport } from './routes/huddles.$huddleSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinearCallbackRoute = LinearCallbackRouteImport.update({
  id: '/linear/callback',
  path: '/linear/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const HuddlesHuddleSlugRoute = HuddlesHuddleSlugRouteImport.update({
  id: '/huddles/$huddleSlug',
  path: '/huddles/$huddleSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/huddles/$huddleSlug': typeof HuddlesHuddleSlugRoute
  '/linear/callback': typeof LinearCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/huddles/$huddleSlug': typeof HuddlesHuddleSlugRoute
  '/linear/callback': typeof LinearCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/huddles/$huddleSlug': typeof HuddlesHuddleSlugRoute
  '/linear/callback': typeof LinearCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/huddles/$huddleSlug' | '/linear/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/huddles/$huddleSlug' | '/linear/callback'
  id: '__root__' | '/' | '/huddles/$huddleSlug' | '/linear/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HuddlesHuddleSlugRoute: typeof HuddlesHuddleSlugRoute
  LinearCallbackRoute: typeof LinearCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linear/callback': {
      id: '/linear/callback'
      path: '/linear/callback'
      fullPath: '/linear/callback'
      preLoaderRoute: typeof LinearCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huddles/$huddleSlug': {
      id: '/huddles/$huddleSlug'
      path: '/huddles/$huddleSlug'
      fullPath: '/huddles/$huddleSlug'
      preLoaderRoute: typeof HuddlesHuddleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HuddlesHuddleSlugRoute: HuddlesHuddleSlugRoute,
  LinearCallbackRoute: LinearCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
